//
//  Data.swift
//  techtogether
//
//  Created by Sofia Ongele on 2/1/20.
//  Copyright © 2020 Sofia Ongele. All rights reserved.
//

import Foundation

class DataStore {
    let locations =  [
            ["name" : "New England Innocence Project",
                         "latitude" : 42.356710,
                         "longitude" : -71.061190,
                         "mediaURL" : "http://www.newenglandinnocence.org/",
                         "phoneNumber" : "6175576582"],
            ["name" : "Committee for Public Counsel Services Innocence Program",
                         "latitude" : 42.374330,
                         "longitude" : -71.082170,
                         "mediaURL" : "https://www.publiccounsel.net/",
                         "phoneNumber" : "6176230591"],
            ["name" : "Boston College Innocence Program",
                         "latitude" : 42.351510,
                         "longitude" : -71.186050,
                         "mediaURL" : "http://www.bc.edu/schools/law/center-experiential-learning/clinical-programs/innocence_programclinic.html",
                         "phoneNumber" : "6175520236"],
            ["name" : "Connecticut Innocence Project/Post-conviction Unit",
                         "latitude" : 41.666460,
                         "longitude" : -72.641370,
                         "mediaURL" : "https://portal.ct.gov/OCPD/Innocence-Project/Connecticut-Innocence-Project",
                         "phoneNumber" : "8602584940"],
            ["name" : "New York Law School Post-Conviction Innocence Clinic",
                         "latitude" : 40.718020,
                         "longitude" : -74.006940,
                         "mediaURL" : "http://www.nyls.edu/academics/office_of_clinical_and_experiential_learning/clinics/post_conviction_innocence_project/",
                         "phoneNumber" : "2124312813"],
            ["name" : "Exoneration Initiative",
                         "latitude" : 40.716770,
                         "longitude" : -74.003550,
                         "mediaURL" : "http://exonerationinitiative.org/",
                         "phoneNumber" : "2129659335"],
            ["name" : "Innocence Project",
                         "latitude" : 40.716880,
                         "longitude" : -74.007010,
                         "mediaURL" : "http://www.innocenceproject.org/",
                         "phoneNumber" : "2123645340"],
            ["name" : "Loyola Law School Project for the Innocent",
                         "latitude" : 34.0491143,
                         "longitude" : -118.2703876,
                         "mediaURL" : "https://www.lls.edu/academics/experientiallearning/clinics/projectfortheinnocent/",
                         "phoneNumber" : "2137368141"],
            ["name" : "Witness to Innocence",
                         "latitude" : 39.9560755,
                         "longitude" : -75.1650982,
                         "mediaURL" : "http://www.witnesstoinnocence.org/",
                         "phoneNumber" : "2675194584​"],
            ["name" : "University of Baltimore Innocence Project Clinic",
                         "latitude" : 39.30342483520508,
                         "longitude" : -76.61605072021484,
                         "mediaURL" : "http://law.ubalt.edu/clinics/innocenceproject.cfm",
                         "phoneNumber" : "4108376543"],
            ["name" : "Mid-Atlantic Innocence Project",
                         "latitude" : 38.9002,
                         "longitude" : -77.012943,
                         "mediaURL" : "http://www.exonerate.org/",
                         "phoneNumber" : "2029944586​"],
            ["name" : "West Virginia Innocence Project",
                         "latitude" : 39.6485793,
                         "longitude" : -79.9585519,
                         "mediaURL" : "https://wvinnocenceproject.law.wvu.edu/",
                         "phoneNumber" : "3042937294​"],
            ["name" : "Innocence Project at UVA School of Law",
                         "latitude" : 38.052279,
                         "longitude" : -78.507713,
                         "mediaURL" : "http://www.law.virginia.edu/html/academics/practical/innocenceclinic.htm",
                         "phoneNumber" : "4349243732"],
            ["name" : "Wake Forest University Law School Innocence and Justice Clinic",
                         "latitude" : 36.133909,
                         "longitude" : -80.27764,
                         "mediaURL" : "http://innocence-clinic.law.wfu.edu/",
                         "phoneNumber" : "3367586111​"],
            ["name" : "North Carolina Center on Actual Innocence",
                         "latitude" : 36.051155,
                         "longitude" : -78.857651,
                         "mediaURL" : "http://www.nccai.org/",
                         "phoneNumber" : "9194893268​"],
            ["name" : "Georgia Innocence Project",
                         "latitude" : 33.7923655,
                         "longitude" : -84.2859848,
                         "mediaURL" : "https://www.georgiainnocenceproject.org/",
                         "phoneNumber" : "4043734433​"],
            ["name" : "Innocence Project of Florida",
                         "latitude" : 30.441749572753906,
                         "longitude" : -84.26793670654297,
                         "mediaURL" : "http://www.floridainnocence.org/",
                         "phoneNumber" : "8505616767​"],
            ["name" : "University of Miami Law Innocence Clinic",
                         "latitude" : 25.719019,
                         "longitude" : -80.276042,
                         "mediaURL" : "http://www.law.miami.edu/academics/clinics/innocence-clinic",
                         "phoneNumber" : "3052848115​"],
            ["name" : "Office of the Ohio Public Defender, Wrongful Conviction Project",
                         "latitude" : 39.96303176879883,
                         "longitude" : -82.99352264404297,
                         "mediaURL" : "http://opd.ohio.gov/Trial-Services/Wrongful-Conviction-Project",
                         "phoneNumber" : "6144665394​"],
            ["name" : "Ohio Innocence Project",
                         "latitude" : 39.319682,
                         "longitude" : -84.366928,
                         "mediaURL" : "https://law.uc.edu/real-world-learning/centers/ohio-innocence-project-at-cincinnati-law.html",
                         "phoneNumber" : "5135560752​"],
            ["name" : "Michigan State Appellate Defender Office - Wrongful Conviction Units",
                         "latitude" : 42.330191,
                         "longitude" : -83.04701,
                         "mediaURL" : "http://www.sado.org/",
                         "phoneNumber" : "3132569833​"],
            




            
    ]
}
